-- Active: 1747886189739@@127.0.0.1@3306@awe_electronics
DROP TABLE IF EXISTS `Reports`;
DROP TABLE IF EXISTS `Receipts`;
DROP TABLE IF EXISTS `Invoices`;
DROP TABLE IF EXISTS `Trolley`;
DROP TABLE IF EXISTS `Accounts`;
DROP TABLE IF EXISTS `Orders`;
DROP TABLE IF EXISTS `Lineitems`;
DROP TABLE IF EXISTS `Products`;
DROP TABLE IF EXISTS `Status`;
DROP TABLE IF EXISTS `Roles`;

CREATE TABLE `Roles` (
	`roleID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE `Status` (
	`statusID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(32) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE `Products` (
	`productID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

) ENGINE=InnoDB;

CREATE TABLE `Lineitems` (
	`lineItemID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

) ENGINE=InnoDB;

CREATE TABLE `Orders` (
	`orderID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

) ENGINE=InnoDB;

CREATE TABLE `Accounts` (
	`accountID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`email` VARCHAR(100) NOT NULL,
	`password` VARCHAR(100) NOT NULL,
	`creationDate` DATETIME NOT NULL,
	`roleID` INT NOT NULL,
	`statusID` INT NOT NULL,
	CONSTRAINT `accounts_FK_roles`FOREIGN KEY `roleID` REFERENCES `roles` (`roleID`) ON UPDATE RESTRICT ON DELETE RESTRICT
	CONSTRAINT `accounts_FK_status`FOREIGN KEY `statusID` REFERENCES `status` (`statusID`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE `Trolley` (
	`trolleyID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

) ENGINE=InnoDB;

CREATE TABLE `Invoices` (
	`invoiceID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

) ENGINE=InnoDB;

CREATE TABLE `Receipts` (
	`receiptID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

) ENGINE=InnoDB;

CREATE TABLE `Reports` (
	`reportID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

) ENGINE=InnoDB;
