DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS trolleys;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS lineitems;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
	roleID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE status (
	statusID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(32) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE products (
	productID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL

) ENGINE=InnoDB;

CREATE TABLE lineitems (
	lineItemID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL

) ENGINE=InnoDB;

CREATE TABLE orders (
	orderID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	customerID INT

) ENGINE=InnoDB;

CREATE TABLE `accounts` (
    `accountID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `creationDate` DATETIME NOT NULL,
    `roleID` INT NOT NULL,
    `statusID` INT NOT NULL,
    CONSTRAINT `accounts_FK_roles` FOREIGN KEY (`roleID`) REFERENCES `roles` (`roleID`) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `accounts_FK_status` FOREIGN KEY (`statusID`) REFERENCES `status` (`statusID`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE trolleys (
	trolleyID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	customerID INT

) ENGINE=InnoDB;

CREATE TABLE invoices (
	invoiceID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	customerID INT

) ENGINE=InnoDB;

CREATE TABLE receipts (
	receiptID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	customerID INT 

) ENGINE=InnoDB;

CREATE TABLE reports (
	reportID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type VARCHAR(50) NOT NULL

) ENGINE=InnoDB;